// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaddleProject.Database;

namespace PaddleProject.Migrations.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200625171001_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaddleProject.Database.Entities.Maker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Makers");
                });

            modelBuilder.Entity("PaddleProject.Database.Entities.Paddle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MakerID")
                        .HasColumnType("int");

                    b.Property<int>("PaddleDimensionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Paddles");
                });

            modelBuilder.Entity("PaddleProject.Database.Entities.PaddleDimension", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("LengthCm")
                        .HasColumnType("float");

                    b.Property<double>("LoomDepthCm")
                        .HasColumnType("float");

                    b.Property<double>("LoomHeightCm")
                        .HasColumnType("float");

                    b.Property<double>("LoomLengthCm")
                        .HasColumnType("float");

                    b.Property<double>("ShoulderLengthCm")
                        .HasColumnType("float");

                    b.Property<double>("TipDepthCm")
                        .HasColumnType("float");

                    b.Property<double>("WidthCm")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("PaddleDimensions");
                });
#pragma warning restore 612, 618
        }
    }
}
