// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaddleProject.Database;

namespace PaddleProject.Migrations.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200625190129_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PaddleProject.Database.Entities.Maker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Makers");
                });

            modelBuilder.Entity("PaddleProject.Database.Entities.Paddle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("MakerID");

                    b.Property<int>("PaddleDimensionID");

                    b.Property<double>("ScaleFactor")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1.0);

                    b.HasKey("ID");

                    b.ToTable("Paddles");
                });

            modelBuilder.Entity("PaddleProject.Database.Entities.PaddleDimension", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("LengthCm");

                    b.Property<double>("LoomDepthCm");

                    b.Property<double>("LoomHeightCm");

                    b.Property<double>("LoomLengthCm");

                    b.Property<double>("ShoulderLengthCm");

                    b.Property<double>("TipDepthCm");

                    b.Property<double>("WidthCm");

                    b.HasKey("ID");

                    b.ToTable("PaddleDimensions");
                });
#pragma warning restore 612, 618
        }
    }
}
